object FrmConfig_Impressoras: TFrmConfig_Impressoras
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Cadastro do terminal'
  ClientHeight = 522
  ClientWidth = 458
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poScreenCenter
  OnCloseQuery = FormCloseQuery
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  TextHeight = 13
  object Shape27: TShape
    Left = 0
    Top = 24
    Width = 458
    Height = 498
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Brush.Style = bsClear
    Pen.Color = clSilver
    ExplicitLeft = 1
    ExplicitHeight = 536
  end
  object Shape16: TShape
    Left = 0
    Top = 0
    Width = 458
    Height = 24
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    Brush.Color = 5986569
    OnMouseDown = Shape16MouseDown
    ExplicitLeft = 13
    ExplicitWidth = 443
  end
  object Label38: TLabel
    Left = 172
    Top = 2
    Width = 276
    Height = 19
    Caption = 'Cadastrando Impressoras'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -19
    Font.Name = 'Lucida Console'
    Font.Style = [fsBold]
    ParentFont = False
    StyleElements = []
  end
  object Shape1: TShape
    Left = 1
    Top = 209
    Width = 455
    Height = 1
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Brush.Style = bsClear
    Pen.Color = 11383299
  end
  object Label3: TLabel
    Left = 13
    Top = 30
    Width = 35
    Height = 16
    Caption = 'Lista'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label1: TLabel
    Left = 13
    Top = 216
    Width = 71
    Height = 16
    Caption = 'Descri'#231#227'o'
    FocusControl = edpimp_descricao
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label4: TLabel
    Left = 327
    Top = 216
    Width = 52
    Height = 16
    Caption = 'Modelo'
    FocusControl = cbpimp_modelo
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label5: TLabel
    Left = 13
    Top = 258
    Width = 39
    Height = 16
    Caption = 'Porta'
    FocusControl = cbpimp_port
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label6: TLabel
    Left = 509
    Top = 48
    Width = 151
    Height = 16
    Caption = 'Taxa de transmiss'#227'o'
    FocusControl = cbpimp_baud
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label7: TLabel
    Left = 509
    Top = 90
    Width = 90
    Height = 16
    Caption = 'Bit de dados'
    FocusControl = cbpimp_data
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label8: TLabel
    Left = 509
    Top = 132
    Width = 64
    Height = 16
    Caption = 'Paridade'
    FocusControl = cbpimp_parity
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label9: TLabel
    Left = 509
    Top = 176
    Width = 105
    Height = 16
    Caption = 'Bits de parada'
    FocusControl = cbpimp_stop
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label10: TLabel
    Left = 509
    Top = 220
    Width = 124
    Height = 16
    Caption = 'Controle de fluxo'
    FocusControl = cbpimp_handshake
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lblMsgRapida: TLabel
    Left = 11
    Top = 480
    Width = 250
    Height = 16
    Caption = 'Pressione [F2] para gravar altera'#231#245'es'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
    StyleElements = []
  end
  object Label2: TLabel
    Left = 13
    Top = 308
    Width = 175
    Height = 16
    Caption = 'Impressora do Windows'
    FocusControl = cbpimp_impressora
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label11: TLabel
    Left = 13
    Top = 357
    Width = 47
    Height = 16
    Caption = 'Linhas'
    FocusControl = cbpimp_impressora
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Shape2: TShape
    Left = 0
    Top = 24
    Width = 458
    Height = 498
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Brush.Style = bsClear
    Pen.Color = clSilver
    ExplicitLeft = 1
    ExplicitHeight = 536
  end
  object Shape3: TShape
    Left = 0
    Top = 24
    Width = 458
    Height = 498
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Brush.Style = bsClear
    Pen.Color = clSilver
    ExplicitLeft = 1
    ExplicitHeight = 536
  end
  object Label13: TLabel
    Left = 208
    Top = 357
    Width = 60
    Height = 16
    Caption = 'Espa'#231'os'
    FocusControl = cbpimp_impressora
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label12: TLabel
    Left = 108
    Top = 357
    Width = 58
    Height = 16
    Caption = 'Colunas'
    FocusControl = cbpimp_impressora
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label14: TLabel
    Left = 327
    Top = 259
    Width = 108
    Height = 16
    Caption = 'Cod. da p'#225'gina'
    FocusControl = cbbLkupPagina
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object cxGrid1: TcxGrid
    Left = 13
    Top = 48
    Width = 427
    Height = 147
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    LookAndFeel.Kind = lfOffice11
    LookAndFeel.NativeStyle = False
    LookAndFeel.SkinName = 'Wibi_Blue'
    object cxGrid1DBTableView1: TcxGridDBTableView
      Navigator.Buttons.CustomButtons = <>
      Navigator.Buttons.First.Visible = False
      Navigator.Buttons.PriorPage.Visible = False
      Navigator.Buttons.Prior.Visible = False
      Navigator.Buttons.Next.Visible = False
      Navigator.Buttons.NextPage.Visible = False
      Navigator.Buttons.Last.Visible = False
      Navigator.Buttons.Insert.Visible = False
      Navigator.Buttons.Append.Visible = True
      Navigator.Buttons.Edit.Visible = False
      Navigator.Buttons.Post.Visible = False
      Navigator.Buttons.Cancel.Visible = False
      Navigator.Buttons.Refresh.Visible = False
      Navigator.Buttons.SaveBookmark.Visible = False
      Navigator.Buttons.GotoBookmark.Visible = False
      Navigator.Buttons.Filter.Visible = False
      Navigator.Visible = True
      ScrollbarAnnotations.CustomAnnotations = <>
      DataController.DataSource = doImpressoras
      DataController.Options = [dcoAssignGroupingValues, dcoSaveExpanding, dcoImmediatePost]
      DataController.Summary.DefaultGroupSummaryItems = <>
      DataController.Summary.FooterSummaryItems = <
        item
          Kind = skCount
        end
        item
          Format = 'R$ ,0.00;-R$ ,0.00'
          Kind = skSum
          FieldName = 'pcxov_valor'
        end>
      DataController.Summary.SummaryGroups = <>
      OptionsBehavior.GoToNextCellOnEnter = True
      OptionsBehavior.ColumnHeaderHints = False
      OptionsCustomize.ColumnFiltering = False
      OptionsCustomize.ColumnGrouping = False
      OptionsCustomize.ColumnMoving = False
      OptionsCustomize.ColumnSorting = False
      OptionsData.Appending = True
      OptionsData.CancelOnExit = False
      OptionsData.Editing = False
      OptionsData.Inserting = False
      OptionsSelection.CellSelect = False
      OptionsView.ColumnAutoWidth = True
      OptionsView.GroupByBox = False
      OptionsView.Indicator = True
      object cxGrid1DBTableView1pimp_id: TcxGridDBColumn
        Caption = 'ID'
        DataBinding.FieldName = 'pimp_id'
        Options.AutoWidthSizable = False
        Width = 58
      end
      object cxGrid1DBTableView1pimp_descricao: TcxGridDBColumn
        Caption = 'Descri'#231#227'o'
        DataBinding.FieldName = 'pimp_descricao'
        Width = 163
      end
      object cxGrid1DBTableView1pimp_modelo: TcxGridDBColumn
        Caption = 'Modelo'
        DataBinding.FieldName = 'pimp_modelo_descr'
        Options.AutoWidthSizable = False
        Width = 97
      end
      object cxGrid1DBTableView1pimp_port: TcxGridDBColumn
        Caption = 'Porta'
        DataBinding.FieldName = 'pimp_port'
        Options.AutoWidthSizable = False
        Width = 56
      end
      object cxGrid1DBTableView1pimp_ativo: TcxGridDBColumn
        Caption = 'Ativo'
        DataBinding.FieldName = 'pimp_ativo'
        HeaderAlignmentHorz = taCenter
        Options.AutoWidthSizable = False
        Width = 39
      end
    end
    object cxGrid1Level1: TcxGridLevel
      GridView = cxGrid1DBTableView1
    end
  end
  object edpimp_descricao: TcxDBTextEdit
    Left = 13
    Top = 232
    DataBinding.DataField = 'pimp_descricao'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 1
    Width = 300
  end
  object ckpimp_hardflow: TcxDBCheckBox
    Left = 507
    Top = 267
    Caption = 'Fluxo de hardware'
    DataBinding.DataField = 'pimp_hardflow'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ImmediatePost = True
    Properties.NullStyle = nssUnchecked
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = [fsBold]
    Style.LookAndFeel.SkinName = 'Whiteprint'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Whiteprint'
    StyleFocused.LookAndFeel.SkinName = 'Whiteprint'
    StyleHot.LookAndFeel.SkinName = 'Whiteprint'
    TabOrder = 10
    Transparent = True
  end
  object ckpimp_softflow: TcxDBCheckBox
    Left = 507
    Top = 292
    Caption = 'Fluxo de software'
    DataBinding.DataField = 'pimp_softflow'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ImmediatePost = True
    Properties.NullStyle = nssUnchecked
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = [fsBold]
    Style.LookAndFeel.SkinName = 'Whiteprint'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Whiteprint'
    StyleFocused.LookAndFeel.SkinName = 'Whiteprint'
    StyleHot.LookAndFeel.SkinName = 'Whiteprint'
    TabOrder = 11
    Transparent = True
  end
  object ckpimp_ativo: TcxDBCheckBox
    Left = 8
    Top = 402
    Caption = 'Ativo'
    DataBinding.DataField = 'pimp_ativo'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ImmediatePost = True
    Properties.NullStyle = nssUnchecked
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = [fsBold]
    Style.LookAndFeel.SkinName = 'Whiteprint'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Whiteprint'
    StyleFocused.LookAndFeel.SkinName = 'Whiteprint'
    StyleHot.LookAndFeel.SkinName = 'Whiteprint'
    TabOrder = 12
  end
  object cbpimp_baud: TcxDBLookupComboBox
    Left = 509
    Top = 64
    DataBinding.DataField = 'pimp_baud'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 5
    Width = 151
  end
  object cbpimp_data: TcxDBLookupComboBox
    Left = 509
    Top = 104
    DataBinding.DataField = 'pimp_data'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 6
    Width = 151
  end
  object cbpimp_parity: TcxDBLookupComboBox
    Left = 509
    Top = 148
    DataBinding.DataField = 'pimp_parity'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 7
    Width = 151
  end
  object cbpimp_stop: TcxDBLookupComboBox
    Left = 509
    Top = 192
    DataBinding.DataField = 'pimp_stop'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 8
    Width = 151
  end
  object cbpimp_handshake: TcxDBLookupComboBox
    Left = 509
    Top = 236
    DataBinding.DataField = 'pimp_handshake'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 9
    Width = 151
  end
  object cbpimp_modelo: TcxDBLookupComboBox
    Left = 327
    Top = 232
    DataBinding.DataField = 'pimp_modelo'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.ListColumns = <>
    Properties.ListOptions.ShowHeader = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 2
    Width = 121
  end
  object cbpimp_impressora: TcxDBComboBox
    Left = 13
    Top = 325
    DataBinding.DataField = 'pimp_impressora'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Properties.DropDownListStyle = lsEditFixedList
    Properties.DropDownRows = 20
    Properties.ImmediatePost = True
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 4
    Width = 300
  end
  object cbpimp_port: TcxDBComboBox
    Left = 13
    Top = 275
    DataBinding.DataField = 'pimp_port'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 3
    Width = 300
  end
  object cxButton1: TcxButton
    Left = 13
    Top = 432
    Width = 300
    Height = 25
    Caption = 'Teste de impress'#227'o'
    TabOrder = 13
    OnClick = cxButton1Click
  end
  object cxSpinLinhas: TcxDBSpinEdit
    Left = 13
    Top = 375
    DataBinding.DataField = 'pimp_linhas'
    DataBinding.DataSource = doImpressoras
    TabOrder = 14
    Width = 80
  end
  object cxSpinColunas: TcxDBSpinEdit
    Left = 109
    Top = 375
    DataBinding.DataField = 'pimp_colunas'
    DataBinding.DataSource = doImpressoras
    TabOrder = 15
    Width = 80
  end
  object cxSpinEspacos: TcxDBSpinEdit
    Left = 208
    Top = 375
    DataBinding.DataField = 'pimp_espacos'
    DataBinding.DataSource = doImpressoras
    TabOrder = 16
    Width = 80
  end
  object cbbLkupPagina: TcxDBComboBox
    Left = 327
    Top = 275
    DataBinding.DataField = 'pimp_codigo_pagina'
    DataBinding.DataSource = doImpressoras
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Verdana'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'Blue'
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'Blue'
    StyleFocused.LookAndFeel.SkinName = 'Blue'
    StyleHot.LookAndFeel.SkinName = 'Blue'
    TabOrder = 17
    Width = 121
  end
  object WiEventsForm1: TWiEventsForm
    IDControl = edpimp_descricao
    OnKeyDownEscape = WiEventsForm1KeyDownEscape
    Left = 353
    Top = 98
  end
  object dsImpressoras: TWiFDQuery
    Connection = FrmPDV_DModule.ADConnection1
    UpdateOptions.AssignedValues = [uvEDelete, uvEInsert, uvEUpdate]
    SQL.Strings = (
      'SELECT * FROM pdv.vw_impressoras')
    CustomDelete = False
    ProcedureName = 'pdv.proc_input_tb_impressoras'
    TableNameDelete = 'pdv.tb_impressoras'
    KeyFieldRefresh = 'pterm_id'
    KeyFieldDelete = 'pterm_id'
    ShowMsgBeforeDelete = False
    ReadOnly = False
    Left = 220
    Top = 96
  end
  object doImpressoras: TDataSource
    DataSet = dsImpressoras
    Left = 292
    Top = 101
  end
  object ACBrPosPrinter1: TACBrPosPrinter
    ConfigBarras.MostrarCodigo = False
    ConfigBarras.LarguraLinha = 0
    ConfigBarras.Altura = 0
    ConfigBarras.Margem = 0
    ConfigQRCode.Tipo = 2
    ConfigQRCode.LarguraModulo = 4
    ConfigQRCode.ErrorLevel = 0
    LinhasEntreCupons = 0
    Left = 320
    Top = 456
  end
end
