object FrmTEFLog: TFrmTEFLog
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FrmTEFLog'
  ClientHeight = 418
  ClientWidth = 604
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Shape27: TShape
    Left = 0
    Top = 0
    Width = 604
    Height = 418
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Brush.Style = bsClear
    Pen.Color = 11383299
    ExplicitLeft = -5
    ExplicitTop = -5
    ExplicitWidth = 407
    ExplicitHeight = 133
  end
  object mem_log: TMemo
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 598
    Height = 412
    Align = alClient
    BorderStyle = bsNone
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 0
    ExplicitLeft = -2
    ExplicitTop = 8
  end
end
