object FrmSATLog: TFrmSATLog
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FrmSATLog'
  ClientHeight = 456
  ClientWidth = 704
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Shape16: TShape
    Left = 0
    Top = 0
    Width = 704
    Height = 24
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    Brush.Color = 5986569
    ExplicitLeft = -177
    ExplicitWidth = 640
  end
  object lblTitle: TLabel
    Left = 4
    Top = 3
    Width = 26
    Height = 16
    Caption = 'Log'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    StyleElements = []
  end
  object Shape27: TShape
    Left = 0
    Top = 24
    Width = 704
    Height = 432
    Margins.Left = 10
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Brush.Style = bsClear
    Pen.Color = 11383299
    ExplicitLeft = -177
    ExplicitTop = -215
    ExplicitWidth = 640
    ExplicitHeight = 455
  end
  object mem_log: TMemo
    AlignWithMargins = True
    Left = 6
    Top = 29
    Width = 690
    Height = 419
    BorderStyle = bsNone
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 0
  end
end
